"""
Autonomy Engine for Hercules Agent.

Integrates SelfEvaluation into the agent's execution flow.
Handles the decision of when to trigger evaluation and correction loops.
"""

import logging
from typing import Dict, Optional, Any, Callable

from .self_evaluation import SelfEvaluation
from hermes_logging import setup_logging

logger = logging.getLogger(__name__)


class AutonomyEngine:
    """
    Manages autonomous cycles including self-evaluation and correction.
    Acts as a wrapper around the agent's result generation.
    """

    def __init__(
        self,
        agent_id: str,
        delegate_func: Optional[Callable] = None,
        max_eval_iterations: int = 3,
        skip_self_evaluation: bool = False
    ):
        """
        Initialize the AutonomyEngine.

        Args:
            agent_id: The ID of the agent (e.g., 'start', 'orchestrator').
            delegate_func: Reference to the delegate_task function for cross-verification.
            max_eval_iterations: Max iterations for self-evaluation loop.
            skip_self_evaluation: If True, bypass self-evaluation (useful for simple tasks).
        """
        self.agent_id = agent_id
        self.skip_self_evaluation = skip_self_evaluation
        
        if not skip_self_evaluation:
            self.evaluator = SelfEvaluation(
                agent_id=agent_id,
                max_iterations=max_eval_iterations,
                delegate_func=delegate_func
            )
        else:
            self.evaluator = None

    def process_result(
        self,
        initial_result: str,
        goal: str,
        context: Optional[str] = ""
    ) -> Dict:
        """
        Process the agent's result through the self-evaluation pipeline.

        Args:
            initial_result: The raw result from the agent's execution.
            goal: The original user goal/request.
            context: Additional context (conversation history, etc.).

        Returns:
            dict: {
                "final_result": str,
                "passed": bool,
                "iterations": int,
                "evaluation_history": list,
                "skipped": bool
            }
        """
        if self.skip_self_evaluation or self.evaluator is None:
            logger.info(f"[AutonomyEngine] Self-evaluation skipped for {self.agent_id}")
            return {
                "final_result": initial_result,
                "passed": True,  # Assume passed if skipped
                "iterations": 0,
                "evaluation_history": [],
                "skipped": True
            }

        logger.info(f"[AutonomyEngine] Processing result for {self.agent_id}")
        
        try:
            eval_loop_result = self.evaluator.run_evaluation_loop(
                initial_result=initial_result,
                goal=goal,
                context=context
            )
            
            return {
                "final_result": eval_loop_result["final_result"],
                "passed": eval_loop_result["passed"],
                "iterations": eval_loop_result["iterations"],
                "evaluation_history": eval_loop_result["evaluation_history"],
                "skipped": False
            }
            
        except Exception as e:
            logger.error(f"[AutonomyEngine] Error during evaluation loop: {e}", exc_info=True)
            # Fallback: return original result to avoid blocking the user
            return {
                "final_result": initial_result,
                "passed": False,
                "iterations": 0,
                "evaluation_history": [{"error": str(e)}],
                "skipped": False
            }

    def should_activate(self, task_complexity: str = "normal") -> bool:
        """
        Determine if self-evaluation should be activated based on task complexity.
        """
        if self.skip_self_evaluation:
            return False
        
        # Example logic: always run for complex tasks, maybe skip for simple queries
        if task_complexity in ["high", "complex", "normal"]:
            return True
        return False


def integrate_with_agent_run(
    agent_instance,
    result: str,
    user_message: str,
    skip_self_evaluation: bool = False
) -> str:
    """
    Helper function to integrate AutonomyEngine with AIAgent.run_conversation().
    
    Args:
        agent_instance: The AIAgent instance (run_agent.py).
        result: The result generated by the agent.
        user_message: The original user message (goal).
        skip_self_evaluation: Flag to skip the process.
        
    Returns:
        str: The polished/final result.
    """
    if skip_self_evaluation:
        return result

    # Assuming agent_instance has an ID or we use a default
    agent_id = getattr(agent_instance, 'agent_id', 'unknown-agent')
    
    # We need a delegate function. In AIAgent, this is likely tools/delegate_tool.py logic.
    # This part requires wiring in run_agent.py.
    delegate_func = getattr(agent_instance, '_delegate_tool_func', None)
    
    engine = AutonomyEngine(
        agent_id=agent_id,
        delegate_func=delegate_func,
        skip_self_evaluation=skip_self_evaluation
    )
    
    processed = engine.process_result(
        initial_result=result,
        goal=user_message,
        context=""  # Can be filled with conversation history if needed
    )
    
    if not processed["passed"]:
        logger = logging.getLogger(__name__)
        logger.warning(
            f"Self-evaluation did not pass after {processed['iterations']} iterations. "
            f"Returning best available result."
        )
    
    return processed["final_result"]
